// covid LOADER
export const GET_COVID_LOADING_REQUEST = "GET_COVID_LOADING_REQUEST";
export const GET_COVID_LOADING_SUCCESS = "GET_COVID_LOADING_SUCCESS";

// current location
export const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";

// covid constants
export const GET_COVID_DATA_REQUEST = "GET_COVID_DATA_REQUEST";
export const GET_COVID_DATA_SUCCESS = "GET_COVID_DATA_SUCCESS";

// covid resource
export const GET_COVID_RESOURCE_REQUEST = "GET_COVID_RESOURCE_REQUEST";
export const GET_COVID_RESOURCE_SUCCESS = "GET_COVID_RESOURCE_SUCCESS";

// covid zones
export const GET_COVID_ZONE_REQUEST = "GET_COVID_ZONE_REQUEST";
export const GET_COVID_ZONE_SUCCESS = "GET_COVID_ZONE_SUCCESS";

// covid state wise
export const GET_COVID_STATEWISE_REQUEST = "GET_COVID_STATEWISE_REQUEST";
export const GET_COVID_STATEWISE_SUCCESS = "GET_COVID_STATEWISE_SUCCESS";

// covid log data
export const GET_COVID_LOG_REQUEST = "GET_COVID_LOG_REQUEST";
export const GET_COVID_LOG_SUCCESS = "GET_COVID_LOG_SUCCESS";

